name 'django-realworld'
maintainer 'Kalin Staykov'
maintainer_email 'k.t.staykov@gmail.com'
license 'MIT'
description 'Installs/Configures django-realworld'
long_description 'Installs/Configures django-realworld'
version '0.1.0'
chef_version '>= 13.0'
issues_url 'https://github.com/kalints/django-realworld/issues'
source_url 'https://github.com/kalints/django-realworld'
supports 'ubuntu'